### ISSUE TITLE
Checkbox value not saved?

### ISSUE THREAD

**Issue by supergiulab** [BenBroide/simple-guten-fields#4]
I cannot get the checkbox field meta to be saved. I registered the field with this code:

`$fields_array[] =
     'meta_key'  => '
     'control'   => 'checkbox',
     'post_type' => 'post',
     'panel' => 'page_settings',
     'type' => 'boolean'
];`

There is something wrong?
Thank you

**Comment by TGDTechdev** [comment]
@supergiulab seems like you don't have a 'meta_key' set set

**Comment by BenBroide** [comment]
@supergiulab i don't see a meta_key set your code

**Comment by supergiulab** [comment]
Sorry I didn't answer more, I must have pasted the code wrong but it seemed to me that it still didn't save the value even with the meta_key.

I will double check the code better, sorry.

Thanks for the feedback
